### ISSUE TITLE
since today: All Entities are stale, unavailable after HA Restart

### ISSUE THREAD

**Issue by LuckyTriple7** [stephan192/hochwasserportal#12]
HA 2023.6.3

![image](https://github.com/stephan192/hochwasserportal/assets/60685158/c41104fb-171b-46a8-8df7-dd4089329473)

Following Errors in the Logfile:

2023-07-03 17:00:14.678 ERROR (SyncWorker_0) [custom_components.hochwasserportal.sensor] Init API - SH_9610010 - Failed!
2023-07-03 17:00:14.708 ERROR (SyncWorker_24) [custom_components.hochwasserportal.sensor] Init API - BW_215 - Failed!
2023-07-03 17:00:14.717 ERROR (SyncWorker_11) [custom_components.hochwasserportal.sensor] Init API - SH_9510070 - Failed!
2023-07-03 17:00:14.789 ERROR (SyncWorker_4) [custom_components.hochwasserportal.sensor] Init API - BW_115 - Failed!
2023-07-03 17:00:14.795 ERROR (SyncWorker_3) [custom_components.hochwasserportal.sensor] Init API - SH_9530020 - Failed!
2023-07-03 17:00:14.840 ERROR (SyncWorker_14) [custom_components.hochwasserportal.sensor] Init API - MV_9650043 - Failed!
2023-07-03 17:00:14.840 ERROR (SyncWorker_19) [custom_components.hochwasserportal.sensor] Init API - SH_110006 - Failed!
2023-07-03 17:00:14.845 ERROR (SyncWorker_10) [custom_components.hochwasserportal.sensor] Init API - BW_7 - Failed!
2023-07-03 17:00:14.882 ERROR (SyncWorker_6) [custom_components.hochwasserportal.sensor] Init API - BW_116 - Failed!
2023-07-03 17:00:14.888 ERROR (SyncWorker_5) [custom_components.hochwasserportal.sensor] Init API - SH_9510095 - Failed!
2023-07-03 17:00:14.896 ERROR (SyncWorker_9) [custom_components.hochwasserportal.sensor] Init API - BW_147 - Failed!
2023-07-03 17:00:14.924 ERROR (SyncWorker_23) [custom_components.hochwasserportal.sensor] Init API - BW_9016 - Failed!
2023-07-03 17:00:14.932 ERROR (SyncWorker_20) [custom_components.hochwasserportal.sensor] Init API - BW_40 - Failed!
2023-07-03 17:00:14.938 ERROR (SyncWorker_12) [custom_components.hochwasserportal.sensor] Init API - BW_38 - Failed!
2023-07-03 17:00:14.960 ERROR (SyncWorker_13) [custom_components.hochwasserportal.sensor] Init API - BW_70 - Failed!

**Comment by stephan192** [comment]
It seems as if the used API has a problem. All queries i've tested return zero data.
Hopefully LHP will fix this problem soon.

For testing you can try.
https://hochwasserzentralen.api.bund.dev/

**Comment by LuckyTriple7** [comment]
The API is still down. For the future it would be great to set up the integration via the Config Flow. A reload is then sufficient and you do not have to restart the entire HA.

**Comment by stephan192** [comment]
I'm already working an a version with config flow. Hope i'll find more spare time to finish it.

**Comment by stephan192** [comment]
I've got response from LHP via Email why it is not working anymore.

They locked the API for external access. They say i was using an API which was not offical released to public and is now only internally available for feeding the LHP homepage with data.

Therefore this is the deadly shot for this integration so far. I currently don't have any clou where to get the data from. The main problem is that every feder state in Germany handles and presents the data in different formats.

**Comment by Eyco1981** [comment]
Not a fix, but kind of good news.
In HA Core 2023.8 the new integration Pegelonline will be introduced.
https://rc.home-assistant.io/integrations/pegel_online

**Comment by Zunhammer** [comment]
This is indeed great news, however this will only provide values for water routes. Personally, I'm livin gin Munich and am interested in the Isar's values which are not available on pegelonline. I guess I somehow need to extract the valuesmanually using regex.

**Comment by Eyco1981** [comment]
For those cases, the Scrape integration might be a workaround - if homepage has usable HTML tags.
There is also a YouTube video in German which explains a bit, how the Scrape sensors in HA can be used.

**Comment by Eyco1981** [comment]
Don't think that would be a solution for this integration. More a workaround for people who cannot get water level data from Pegelonline

**Comment by nohn** [comment]
It seems like the state portals still provide data: `curl 'https://hochwasserportal.nrw/lanuv/data/internet/stations/100/2727500000100/index.json`

**Comment by Zunhammer** [comment]
Did anyone try this API (or is this even the former used one?): https://hochwasserzentralen.api.bund.dev/

I'm not able to make it run but it seems somehow official...

**Comment by nohn** [comment]
That’s the API, this plug-in uses. bund.dev intentionally looks official, but unfortunately it isn’t.

**Comment by stephan192** [comment]
I'm currently testing a version which is able to get the Bavarian values by scraping https://www.hnd.bayern.de/pegel
First test results are looking good. Seems as if 1 out of 16 states is done.

**Comment by nohn** [comment]
@stephan192 would you mind pushing that to a branch so I could use it as a base for NRW?

**Comment by stephan192** [comment]
I've made a new release which should work for Bavaria.
Right at the time LHP locked the API i was working on a switch to config flow, so i finished this action first.
@nohn look in the api.py and fill parse_init_NW() and parse_NW() with content like i did for Bavaria. Use web scraping or an api, whatever they offer.
I'll try integrating Schleswig-Holstein meanwhile.

**Comment by nohn** [comment]
I'm trying to figure out how to translate the values to stages. However: Hochwasserzentralen and this component is speaking of 5 (0 to 4) levels, while apparently both in the NW JSON and website I can only find 4 (0 to 3): 

![image](https://github.com/stephan192/hochwasserportal/assets/113465/0a026ab7-20c3-468f-99ae-d96dd91e3006)

Any idea?

Flow is very likely not going to happen for NW. Didn't work with Hochwasserzentralen either.

**Comment by Zunhammer** [comment]
> 

Thanks for your efforts! May I ask how to setup the new method, old config is not working anymore :) Couldn't find any description in the readme yet.
Thanks

**Comment by stephan192** [comment]
> 
> Any idea?
> 
According to the following list in NRW there are only level 0 to 3. 4 doesn't seem to exist.

https://www.hochwasserzentralen.de/info

**Comment by stephan192** [comment]
> > 
> 
> Thanks for your efforts! May I ask how to setup the new method, old config is not working anymore :) Couldn't find any description in the readme yet.
> Thanks

See the configuration section in the readme. New entries can be added via the GUI like most Integrations now.
Old entries should have been imported.

**Comment by Dennis1000** [comment]
BW pegels can be found here 
www.hvz.baden-wuerttemberg.de/js/hvz_peg_stmn.js

**Comment by makanimike** [comment]
on the main page it says that NRW (NW) is working already.  
But when I try to add it when adding the Integration it says the Pegel ID is invalid. I tried both with and without "NW_". And I tried three different Pegels, just in case it was only mine that has issues.  
  
Did I misunderstand? Do you still need to do something for NRW?

**Comment by nohn** [comment]
@makanimike which ones are you trying?

**Comment by makanimike** [comment]
> @makanimike which ones are you trying?

I need NW_2750010 | Düsseldorf / Rhein.

I also tried   
NW_2730010	Köln / Rhein
NW_2710080	Bonn / Rhein

**Comment by stephan192** [comment]
@makanimike i made a new release.
Now the pegel should work.
Attention:  Düsseldorf has a new id NW_27500100 (one additional zero)
See updated pegel.md

**Comment by makanimike** [comment]
It looks like the issue came back? at least for duesseldorf (and bonn that I did for a quick cross-check).  
  
It's not working for me since the last update, I believe. (it's a bit difficult to say because there have been a lot of updates in the last week or so) :)
