### ISSUE TITLE
Source: custom_components/hochwasserportal/sensor.py:53

### ISSUE THREAD

**Issue by Johnyboy1984** [stephan192/hochwasserportal#13]
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.hochwasserportal.sensor
Source: custom_components/hochwasserportal/sensor.py:53
Integration: hochwasserportal (documentation, issues)
First occurred: 13:28:11 (33 occurrences)
Last logged: 13:28:12

Init API - RP_27100700 - Failed!
Init API - RP_26560103 - Failed!
Init API - RP_25100300 - Failed!
Init API - RP_23900200 - Failed!
Init API - RP_26200505 - Failed!

**Comment by stephan192** [comment]
Dublicate see #12
