### ISSUE TITLE
No data from Swiss rivers

### ISSUE THREAD

**Issue by Balou067** [stephan192/hochwasserportal#4]
I added the Hochwasserportal Integration and data from German rivers are shown but not for Swiss rivers.

German rivers I configured and data are correctly shown are: BY_16003003, BY_16003502, BY_16005701
Swiss rivers I configured and NO data are shown are: CH_2087, CH_2152, CH_2110, CH_2018

Any idea why the Swiss river do not work? The only difference in the configuration is the pegel-id.

**Comment by stephan192** [comment]
That not true, the swiss ones are working but they only report a stage.

Quote from README.md
> Not all stream gauges report all three values. If one or more values are unavailable check official site if stream gauge is down or if not which values are reported.

I you have a look on the offical site https://www.hochwasserzentralen.de you will see that all swiss gauges only report a stage and neither level nor flow.
