### ISSUE TITLE
Speicherbauwerk: Pegelstand/Füllstand und Warnstufe nicht verfügbar

### ISSUE THREAD

**Issue by lebochequirit** [stephan192/hochwasserportal#41]
Betrifft das HWRB Salzderhelden / Leine (NI_10110)
Der Sensor Durchfluss wird abgerufen,
Volumen/Füllstand und Warnstufe nicht.

Kann daran liegen, dass der json-String bei Speicherbauwerken anders aufgebaut ist.

Sehr hilfreiche Integration übrigens, vielen Dank dafür.

**Comment by stephan192** [comment]
Hallo @lebochequirit,

ja, bei Speicherbauwerken sind die Rohdaten anders aufgebaut.
Für dein Beispiel findest du die Rohdaten hier: https://bis.azure-api.net/PegelonlinePublic/REST/stammdaten/stationen/639?key=9dc05f4e3b4a43a9988d747825b39f43
Im Block Parameter findet man den Durchfluss mit dem Hinweis ohne Meldestufe.

Zwar findet man hier auch den Füllstand, aber da es deutschlandweit kaum ähnliche Pegel gibt wird der Wert nicht ausgelesen und weiterverarbeitet.
