### ISSUE TITLE
Pegel Leine/Herrenhausen not found

### ISSUE THREAD

**Issue by lebochequirit** [stephan192/hochwasserportal#42]
https://www.pegelonline.nlwkn.niedersachsen.de/Pegel/Binnenpegel/ID/325
https://m.pegelonline.wsv.de/gast/stammdaten?pegelnr=48800108

Would have added it to pegel.md myself, but don't know how the IDs are translated (Like Koldingen/Leine ID478 to NI_4887101).

**Comment by stephan192** [comment]
Hi @lebochequirit,
the [pegel.md](https://github.com/stephan192/hochwasserportal/blob/main/pegel.md) is autogenerated by the script [update_pegel_list.py](https://github.com/stephan192/hochwasserportal/blob/main/update_pegel_list.py) approx. every two weeks.

For Niedersachen e.g. it uses https://bis.azure-api.net/PegelonlinePublic/REST/stammdaten/stationen/All?key=9dc05f4e3b4a43a9988d747825b39f43 as data source. Leine/Herrenhausen isn't listed there, so it is not accessible. If NLWKN adds it there is will be added to pegel.md.

Have you tried the [official PEGELONLINE intergration](https://www.home-assistant.io/integrations/pegel_online/)?
