### ISSUE TITLE
Flow doesn't work

### ISSUE THREAD

**Issue by JayZiii** [stephan192/hochwasserportal#5]
Hi there,
the flow sensor doesn't work.

![grafik](https://user-images.githubusercontent.com/72706820/212845096-ae8762ea-00e8-4ef9-96fa-e408a422ebd5.png)

**Comment by stephan192** [comment]
This is not an error. The value is simply not provided by the LHP (no Q value on official site).

**Quote from my README.md:**
> Not all stream gauges report all three values. If one or more values are unavailable check [official site](https://www.hochwasserzentralen.de/) if stream gauge is down or if not which values are reported.
