### ISSUE TITLE
Grundwasserspiegel 

### ISSUE THREAD

**Issue by chiefymuc** [stephan192/hochwasserportal#54]
### Is your feature request related to a problem? Please describe.

No it's an additional feature.

### Describe the solution you'd like

NLWKN also offers Grundwasserspiegel information. Would it be easy for you to introduce this as a feature? It will help to get ready to protect the property if the level gets high.

Thanks for the great work on this integration anyway!

**Comment by stephan192** [comment]
Hi @chiefymuc i'm not planning to implement this feature because it would bring to much data, not related to Hochwasser, into the integration. The request is worth it's own integration.

**Comment by bac1x** [comment]
I think the groundwater level idea is good Wouldn't it be basically the same structure, just read out different databases?

**Comment by stephan192** [comment]
Yes, in principle it is the same, but in detail you probably have to rewrite almost everything, especially for the portals that are queried via web scraping.

But beware: The main work is not the actual integration but the used API. For the hochwasserportal intergration e.g. the used API can be found under https://github.com/stephan192/lhpapi.
