### ISSUE TITLE
Portal has changed

### ISSUE THREAD

**Issue by Cyrelion** [stephan192/hochwasserportal#57]
### Home Assistant version

2024.12.5

### Hochwasserportal integration version

1.0.1

### Affected pegel

NW_2725910000100

### What happened

Integration isn't able to complete "setup"

https://hochwasserportal.nrw/lanuv/data/internet/stations/stations.json

now returns an 404:

Not Found
The requested URL was not found on this server.

See log:

Setup of NW_2725910000100 failed: nw_api.py: init_NW(): HTTPError: 404 Client Error: Not Found for url: https://hochwasserportal.nrw/lanuv/data/internet/stations/stations.json
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/lhpapi/nw_api.py", line 85, in init_NW
    (name, internal_url, url) = get_basic_station_data(ident)
                                ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/lhpapi/nw_api.py", line 21, in get_basic_station_data
    nw_stations = fetch_json(
        "https://hochwasserportal.nrw/lanuv/data/internet/stations/stations.json"
    )
  File "/usr/local/lib/python3.13/site-packages/lhpapi/api_utils.py", line 50, in fetch_json
    response.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://hochwasserportal.nrw/lanuv/data/internet/stations/stations.json


### Reproduction steps

Install HACS Integration :-)

### Relevant log output

```shell
Setup of NW_2725910000100 failed: nw_api.py: init_NW(): HTTPError: 404 Client Error: Not Found for url: https://hochwasserportal.nrw/lanuv/data/internet/stations/stations.json
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/lhpapi/nw_api.py", line 85, in init_NW
    (name, internal_url, url) = get_basic_station_data(ident)
                                ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/lhpapi/nw_api.py", line 21, in get_basic_station_data
    nw_stations = fetch_json(
        "https://hochwasserportal.nrw/lanuv/data/internet/stations/stations.json"
    )
  File "/usr/local/lib/python3.13/site-packages/lhpapi/api_utils.py", line 50, in fetch_json
    response.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://hochwasserportal.nrw/lanuv/data/internet/stations/stations.json
```

**Comment by stephan192** [comment]
Hi @Cyrelion i don't think that the portal has changed. For me it looks as if the portal is currently down.
If you have a look at https://www.hochwasserzentralen.de you can see that all NRW Pegel have been updated yesterday (22.12.2024 at 14:30) for the last time until now. In addition https://hochwasserportal.nrw/lanuv/webpublic/index.html#/Start shows no data.

This is not the first time that a state portal is down. I recommend waiting a few days, because they typically fix it within a few days.

**Comment by stephan192** [comment]
Hi @Cyrelion, it seems as if LANUV has fixed their portal. NW_2725910000100 is working for me again. Can you please confirm and close this issue.

**Comment by Cyrelion** [comment]
You’re right. Sorry for bothering you
