### ISSUE TITLE
Water levels can no longer be called up

### ISSUE THREAD

**Issue by Johnyboy1984** [stephan192/hochwasserportal#6]
The following water levels cannot currently be called up:

RP_25800506 Diez / Lahn
RP_25800608 Kalkhofen / Lahn

If you called it with the following code, it worked without any problems until 8 weeks ago:

#Level Diez Lahn
sensor:
   - platform: hochwasserportal
     level: RP_25800506
     level: True
     stage: True
     flow: True

#Level Kalkhofen Lahn
  - platform: hochwasserportal
     level: RP_25800608
     level: True
     stage: True
     flow: True

**Comment by stephan192** [comment]
The pegel id's have changed. I've just updated the pegel.md.
Your ids are now RP_25800500 and RP_25800600.
Please check and close if ok.

**Comment by Johnyboy1984** [comment]
Good evening,

Thank you for the quick change. I tested the change and it works as expected. Thanks a lot for this.
